-- MySQL Script generated by MySQL Workbench
-- qua 17 mai 2017 19:03:19 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema iotvddb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema iotvddb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `iotvddb` DEFAULT CHARACTER SET utf8 ;
USE `iotvddb` ;

-- -----------------------------------------------------
-- Table `iotvddb`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iotvddb`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `usuario` VARCHAR(50) NOT NULL,
  `email` VARCHAR(80) NOT NULL,
  `senha` VARCHAR(70) NOT NULL,
  `status` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `usuario_UNIQUE` (`usuario` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iotvddb`.`dispositivos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iotvddb`.`dispositivos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `id_usuario` INT NOT NULL,
  `status` TINYINT(1) NOT NULL DEFAULT 1,
  `key` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`, `id_usuario`),
  INDEX `fk_Dispositivos_Usuarios_idx` (`id_usuario` ASC),
  UNIQUE INDEX `key_UNIQUE` (`key` ASC),
  CONSTRAINT `fk_Dispositivos_Usuarios`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `iotvddb`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iotvddb`.`registros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iotvddb`.`registros` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `time` TIMESTAMP NOT NULL,
  `chave` VARCHAR(45) NOT NULL,
  `valor` DOUBLE NOT NULL,
  `id_dispositivo` INT NOT NULL,
  `status` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`, `id_dispositivo`),
  INDEX `fk_Registros_Dispositivos1_idx` (`id_dispositivo` ASC),
  CONSTRAINT `fk_Registros_Dispositivos1`
    FOREIGN KEY (`id_dispositivo`)
    REFERENCES `iotvddb`.`dispositivos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iotvddb`.`loglogin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iotvddb`.`loglogin` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `time` TIMESTAMP NOT NULL,
  `id_usuario` INT NOT NULL,
  `navegador` VARCHAR(100) NULL,
  `latitude` DOUBLE NULL,
  `longitude` DOUBLE NULL,
  PRIMARY KEY (`id`, `id_usuario`),
  INDEX `fk_logslogin_usuarios1_idx` (`id_usuario` ASC),
  CONSTRAINT `fk_logslogin_usuarios1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `iotvddb`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
